### ISSUE TITLE
Sitemap optimization

### ISSUE THREAD

**Issue by Atyc** [raulir/bccms#126]
There should be a way of removing items from sitemap.xml
For example: 
- Pages - http://www.eidyia.co.uk/single-article/ (Page exists to display individual list items)
- Hidden list items - http://www.eidyia.co.uk/copy-of-five-ways-in-which-coaching-can-help-your/
- Links that do not exist - http://www.eidyia.co.uk/new-page/

The hidden list items should be automatically excluded. 
For all the rest, a textarea in the settings page can be used to add each link to be excluded on a separate line

**Comment by raulir** [comment]
http://www.eidyia.co.uk/new-page/

This page seems to exist, just being empty. Maybe pages without visible panels on it should be excluded as well, because by default all new stuff should appear in sitemap.

I think that on page editing cms page, there should be a dropdown to remove the page from sitemap. (near slug input)

Individual list item page should be solved with #106 - there should be special treatment to list item pages through all the cms (but so long the dropdown would do the thing).

I added "router" label for all sitemap, slug, urls, router etc related issues and ideas :)

**Comment by raulir** [comment]
There are now options, where no route or sitemap item is created:

- Hide pages, except homepage (cms_page_id == 1) and list item pages
- When page doesn't contain any non-hidden panels
- When list item is hidden

Should do for now - may need some more testing and some UX improvement.
